### ISSUE TITLE
A4 - Provided .ipynb file loads all cells as text/markdown cells

### ISSUE THREAD

**Issue by JayJaewonYoo** [BME1478H/Winter2022class#399]
When I tried to load the provided .ipynb file for the assignment, last_first_assignment4.ipynb, all the cells were loaded in as text/Markdown cells. This image demonstrates how the file is loaded in for me:
![error_img](https://user-images.githubusercontent.com/39362841/152448998-63c5908a-bd00-4735-8221-0d5ae05b56b7.PNG)

Is anyone else having this issue? I could convert the cells to code cells myself but I want to make sure I'm converting the correct cells so if this is an issue that multiple people are having, would it be possible to provide a version where the cells intended to contain code are code cells since I want to make sure I'm not missing any cells that are supposed to be code cells.

**Comment by RayNele** [comment]
I think you can just run the whole ipynb again?

**Comment by petersuderman** [comment]
I converted all the cells that start with "#" or "#TODO" to code and left everything else and it worked fine for me.

**Comment by RayNele** [comment]
Hi @JayJaewonYoo ,

Sorry I didn't realize this problem was so widespread and couldn't reproduce the issue away from computer (Sometimes markdown just breaks on notebook and all you have to do is restart it). I've attached a fixed version.

[last_first_assignment4_FIXED.zip](https://github.com/BME1478H/Winter2022class/files/8017627/last_first_assignment4_FIXED.zip)

Definitely my fault for not checking. I apologize for that. For future reference, feel free to respond with a "I already tried your solution" or more people chiming in would alert me that this is not a single-instance problem.
